In [28]:
import tensorflow as tf
from edward2 import Normal, Exponential
from edward2 import MultivariateNormalTriL, Dirichlet
tf.enable_eager_execution()

In [17]:
Normal(loc=tf.constant(0.0),scale=tf.constant(1.0))

<ed.RandomVariable 'Normal/' shape=() dtype=float32 numpy=-0.27637053>

In [24]:
Normal(loc=tf.zeros(5),scale=tf.ones(5))

<ed.RandomVariable 'Normal/' shape=(5,) dtype=float32 numpy=
array([ 1.3628325 , -0.04575216,  0.3711778 , -0.34498933, -1.3420787 ],
      dtype=float32)>

In [27]:
Exponential(rate=tf.ones([2,5]))

<ed.RandomVariable 'Exponential/' shape=(2, 5) dtype=float32 numpy=
array([[1.4537061 , 0.0830395 , 2.4423993 , 1.1898628 , 0.5392791 ],
       [1.5179116 , 1.0663519 , 0.96865153, 2.839847  , 0.058229  ]],
      dtype=float32)>

In [39]:
Dirichlet(concentration=tf.constant([1.0]*5))

<ed.RandomVariable 'Dirichlet/' shape=(5,) dtype=float32 numpy=
array([0.10275589, 0.19711241, 0.27766868, 0.02973432, 0.39272866],
      dtype=float32)>

In [41]:
MultivariateNormalTriL(loc=tf.constant([5]),scale_tril=tf.constant(1.0))

ValueError: Argument tril must have at least 2 dimensions.  Found: tf.Tensor(1.0, shape=(), dtype=float32)